parameters:
#    espend_inspector_frontend.example.class: espend\Inspector\FrontendBundle\Example

services:
    espend_inspector_frontend.sitemap_generator:
        class: espend\Inspector\FrontendBundle\Util\SitemapGenerator
        arguments: ['@doctrine.orm.entity_manager', '@espend_inspector_frontend.twig.twigpath_extension']

    espend_inspector_frontend.twig.twigpath_extension:
        class: espend\Inspector\FrontendBundle\Twig\TwigPathExtension
        arguments: ['@router']
        tags:
           - { name: twig.extension }

    espend_inspector_frontend.repository.frontpage:
        class: espend\Inspector\FrontendBundle\Repository\FrontpageRepository
        arguments: ['@fos_elastica.index.code_usage']

    espend_inspector_frontend.repository.class:
        class: espend\Inspector\FrontendBundle\Repository\ClassRepository
        arguments: ['@fos_elastica.index.code_usage']

    espend_inspector_frontend.repository.usage_repository:
        class: espend\Inspector\FrontendBundle\Repository\UsageRepository
        arguments: ['@fos_elastica.index.code_usage']