parameters:
#    espend_inspector_core.example.class: espend\Inspector\CoreBundle\Example

services:
    espend_inspector_core.dbal_query:
        class: espend\Inspector\CoreBundle\Doctrine\DbalQuery
        arguments: ['@doctrine.dbal.default_connection']


    espend_inspector_core.context:
        class: espend\Inspector\FrontendBundle\Context\ClassContextContainer
        arguments: ['@request_stack', '@doctrine.orm.entity_manager']
