espend\Inspector\CoreBundle\Entity\InspectorClass:
    type: entity
    table: inspector_class
    repositoryClass: InspectorClassRepository
    uniqueConstraints:
        class_idx:
            columns: class
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        class:
            type: string
        doc_comment:
            type: string
        last_found_at:
            type: date
    manyToOne:
        project:
            targetEntity: espend\Inspector\CoreBundle\Entity\InspectorProject
    lifecycleCallbacks: {  }
