espend\Inspector\CoreBundle\Entity\InspectorAuthorClass:
    type: entity
    table: inspector_author_class
    repositoryClass: InspectorAuthorClassRepository
    uniqueConstraints:
        class_idx:
            columns: author_id, class_id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        last_found_at:
            type: date
    manyToOne:
        author:
            targetEntity: espend\Inspector\CoreBundle\Entity\InspectorAuthor
            joinColumn:
                onDelete: CASCADE
        class:
            targetEntity: espend\Inspector\CoreBundle\Entity\InspectorClass
            inversedBy: author_class
            joinColumn:
                onDelete: CASCADE
    lifecycleCallbacks: {  }
