espend\Inspector\CoreBundle\Entity\InspectorClass:
    type: entity
    table: inspector_class
    repositoryClass: InspectorClassRepository
    indexes:
        weight_idx:
            columns: weight
    uniqueConstraints:
        class_idx:
            columns: class
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        class:
            type: string
        doc_comment:
            type: text
            nullable: true
        last_found_at:
            type: date
        weight:
            type: integer
            nullable: true
    manyToOne:
        project:
            targetEntity: espend\Inspector\CoreBundle\Entity\InspectorProject
        file:
            targetEntity: espend\Inspector\CoreBundle\Entity\InspectorFile
    oneToMany:
        author_class:
            targetEntity: espend\Inspector\CoreBundle\Entity\InspectorAuthorClass
            mappedBy: class
    lifecycleCallbacks: {  }
