espend\Inspector\CoreBundle\Entity\InspectorProject:
    type: entity
    table: inspector_projects
    repositoryClass: InspectorProjectRepository
    indexes:
        name_idx:
            columns: name
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            nullable: true
            unique: true
        source_url:
            type: string
            nullable: true
        homepage:
            type: string
            nullable: true
        version:
            type: string
            nullable: true
        source_reference:
            type: string
            nullable: true
        downloads:
            type: integer
            nullable: true
            default: 0
        last_found_at:
            type: date
    lifecycleCallbacks: {  }
