espend\Inspector\CoreBundle\Entity\InspectorMethod:
    type: entity
    table: inspector_methods
    repositoryClass: espend\Inspector\CoreBundle\Entity\InspectorMethodRepository
    indexes:
        method_idx:
            columns: method
    uniqueConstraints:
        file_unique:
            columns: key_unique, file_id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        context:
            type: array
            nullable: true
        method:
            type: string
        line:
            type: integer
        last_found_at:
            type: date
        weight:
            type: integer
            nullable: true
        key:
            type: string
            column: key_unique
    manyToOne:
        class:
            targetEntity: espend\Inspector\CoreBundle\Entity\InspectorClass
        file:
            targetEntity: espend\Inspector\CoreBundle\Entity\InspectorFile
    lifecycleCallbacks: {  }
