parameters:
#    espend_inspector_import.example.class: espend\Inspector\ImportBundle\Example

services:
#    espend_inspector_import.example:
#        class: %espend_inspector_import.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
