<?php

namespace espend\Inspector\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InspectorSuperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectorSuperRepository extends EntityRepository
{
    public function getClassCount($classId) {

        $qb = $this->createQueryBuilder('inst');
        $qb->select('count(inst.id)');
        $qb->andWhere('inst.class = :class');
        $qb->setParameter('class', $classId);

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getSubClassesIds($class_id) {

        /** @var InspectorSuper[] $supers */
        $supers = $this->findBy(array(
            'child' => $class_id,
        ));

        $class_ids = array($class_id);
        foreach ($supers as $super) {
            $class_ids[] = $super->getClass()->getId();
        }

        return array_unique($class_ids);
    }
}
