<?php

namespace espend\Inspector\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InspectorInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectorInstanceRepository extends EntityRepository
{

    public function getClassCount($class_ids) {

        $qb = $this->createQueryBuilder('inst');
        $qb->select('count(inst.id)');
        $qb->andWhere($qb->expr()->in('inst.class', (array) $class_ids));

        return $qb->getQuery()->getSingleScalarResult();
    }

}
